services:

  apache:
    container-name: apache
    image:
    restart: unless-stopped
    ports:
      -
      -
    volumes:
      - ./git-dir/web:
    networks:
      default:


  my-sql:
    container-name: my-sql
    image:
    restart: unless-stopped
    ports:
      -
      -
    volumes:
      -
    networks:
      default:
