services:

  apache:
    container_name: apache
    image: php:8.3-apache
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /home/vm/git-dir/web:/var/www/html
    networks:
      default:


#  my-sql:
#    container-name: my-sql
#    image:
#    restart: unless-stopped
#    ports:
#      -
#      -
#    volumes:
#      -
#    networks:
#      default:
